In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the CSVs into a DataFrame
season_22_23 = pd.read_csv('./Basketball_Data/2022-2023_season.csv')
season_21_22 = pd.read_csv('./Basketball_Data/2021-2022_season.csv')
season_20_21 = pd.read_csv('./Basketball_Data/2020-2021_season.csv')

In [3]:
#add seasons dataframes together
multiple_seasons = pd.concat([season_22_23, season_21_22, season_20_21]).reset_index(drop=True)
multiple_seasons

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,Tue Oct 18 2022,7:30p,Philadelphia 76ers,117,Boston Celtics,126,Box Score,NaN,19156.0,TD Garden,NaN
1,Tue Oct 18 2022,10:00p,Los Angeles Lakers,109,Golden State Warriors,123,Box Score,NaN,18064.0,Chase Center,NaN
2,Wed Oct 19 2022,7:00p,Orlando Magic,109,Detroit Pistons,113,Box Score,NaN,20190.0,Little Caesars Arena,NaN
3,Wed Oct 19 2022,7:00p,Washington Wizards,114,Indiana Pacers,107,Box Score,NaN,15027.0,Gainbridge Fieldhouse,NaN
4,Wed Oct 19 2022,7:30p,Houston Rockets,107,Atlanta Hawks,117,Box Score,NaN,17878.0,State Farm Arena,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3673,Sun May 30 2021,3:30p,Phoenix Suns,100,Los Angeles Lakers,92,Box Score,NaN,8025.0,STAPLES Center,NaN
3674,Sun May 30 2021,7:00p,Brooklyn Nets,141,Boston Celtics,126,Box Score,NaN,17226.0,TD Garden,NaN
3675,Sun May 30 2021,9:30p,Los Angeles Clippers,106,Dallas Mavericks,81,Box Score,NaN,17761.0,American Airlines Center,NaN
3676,Mon May 31 2021,7:00p,Philadelphia 76ers,114,Washington Wizards,122,Box Score,NaN,10665.0,Capital One Arena,NaN
3677,Mon May 31 2021,9:30p,Utah Jazz,120,Memphis Grizzlies,113,Box Score,NaN,12185.0,FedEx Forum,NaN

In [4]:
# Drop multiple columns
columns_to_drop = ['Unnamed: 6', 'Unnamed: 7', 'Attend.', 'Arena', 'Notes', 'Start (ET)']
multiple_seasons.drop(columns=columns_to_drop, axis=1, inplace=True)

multiple_seasons

                 Date       Visitor/Neutral  PTS           Home/Neutral  PTS.1
0     Tue Oct 18 2022    Philadelphia 76ers  117         Boston Celtics    126
1     Tue Oct 18 2022    Los Angeles Lakers  109  Golden State Warriors    123
2     Wed Oct 19 2022         Orlando Magic  109        Detroit Pistons    113
3     Wed Oct 19 2022    Washington Wizards  114         Indiana Pacers    107
4     Wed Oct 19 2022       Houston Rockets  107          Atlanta Hawks    117
...               ...                   ...  ...                    ...    ...
3673  Sun May 30 2021          Phoenix Suns  100     Los Angeles Lakers     92
3674  Sun May 30 2021         Brooklyn Nets  141         Boston Celtics    126
3675  Sun May 30 2021  Los Angeles Clippers  106       Dallas Mavericks     81
3676  Mon May 31 2021    Philadelphia 76ers  114     Washington Wizards    122
3677  Mon May 31 2021             Utah Jazz  120      Memphis Grizzlies    113

[3678 rows x 5 columns]

In [18]:
# Loop through the column names and replace the .1's with Home/Visitor Score
new_column_names = {}
for col in multiple_seasons.columns:
    if col.endswith('.1'):
        new_column_names[col] = col.replace('PTS.1', 'Home Score')
    elif col.endswith('PTS'):
        new_column_names[col] = col.replace('PTS', 'Visitor Score')

# Rename the columns
multiple_seasons.rename(columns=new_column_names, inplace=True)

# Rename the Visitor home columns.
multiple_seasons.rename(columns={
    'Visitor/Neutral': 'Visiting Team',
    'Home/Neutral': 'Home Team'
}, inplace=True)

# Show the DataFrame after renaming columns
print("After renaming columns:")
multiple_seasons

After renaming columns:

,Date,Visiting Team,Visitor Score,Home Team,Home Score
0,Tue Oct 18 2022,Philadelphia 76ers,117,Boston Celtics,126
1,Tue Oct 18 2022,Los Angeles Lakers,109,Golden State Warriors,123
2,Wed Oct 19 2022,Orlando Magic,109,Detroit Pistons,113
3,Wed Oct 19 2022,Washington Wizards,114,Indiana Pacers,107
4,Wed Oct 19 2022,Houston Rockets,107,Atlanta Hawks,117
...,...,...,...,...,...
3673,Sun May 30 2021,Phoenix Suns,100,Los Angeles Lakers,92
3674,Sun May 30 2021,Brooklyn Nets,141,Boston Celtics,126
3675,Sun May 30 2021,Los Angeles Clippers,106,Dallas Mavericks,81
3676,Mon May 31 2021,Philadelphia 76ers,114,Washington Wizards,122
3677,Mon May 31 2021,Utah Jazz,120,Memphis Grizzlies,113

In [19]:
# Convert to datetime format
multiple_seasons['Date'] = pd.to_datetime(multiple_seasons['Date'], format='%a %b %d %Y')

multiple_seasons

,Date,Visiting Team,Visitor Score,Home Team,Home Score
0,2022-10-18,Philadelphia 76ers,117,Boston Celtics,126
1,2022-10-18,Los Angeles Lakers,109,Golden State Warriors,123
2,2022-10-19,Orlando Magic,109,Detroit Pistons,113
3,2022-10-19,Washington Wizards,114,Indiana Pacers,107
4,2022-10-19,Houston Rockets,107,Atlanta Hawks,117
...,...,...,...,...,...
3673,2021-05-30,Phoenix Suns,100,Los Angeles Lakers,92
3674,2021-05-30,Brooklyn Nets,141,Boston Celtics,126
3675,2021-05-30,Los Angeles Clippers,106,Dallas Mavericks,81
3676,2021-05-31,Philadelphia 76ers,114,Washington Wizards,122
3677,2021-05-31,Utah Jazz,120,Memphis Grizzlies,113

In [20]:
# Calculate the average of all values in 'Column1'
Visitor_Score_Average = multiple_seasons['Visitor Score'].mean()
Home_Score_Average = multiple_seasons['Home Score'].mean()

print(f'Home average is {Home_Score_Average}, Visitor Score Average is {Visitor_Score_Average}. Total Home Court Advantage is {Home_Score_Average-Visitor_Score_Average}')

Home average is 113.28493746601414, Visitor Score Average is 111.48640565524742. Total Home Court Advantage is 1.7985318107667183

In [31]:
# Create new columns for storing days since last game for Visitor and Home teams
multiple_seasons['Visitor_Last_Game'] = 0
multiple_seasons['Home_Last_Game'] = 0

# Dictionary to keep track of the last game date for each team
last_game_date = {}

# Loop through each row of the DataFrame
for index, row in multiple_seasons.iterrows():
    visitor = row['Visiting Team']
    home = row['Home Team']
    current_date = row['Date']

    # Update Visitor_Last_Game
    if visitor in last_game_date:
        multiple_seasons.at[index, 'Visitor_Last_Game'] = (current_date - last_game_date[visitor]).days
    last_game_date[visitor] = current_date  # Update the last game date for this visitor team

    # Update Home_Last_Game
    if home in last_game_date:
        multiple_seasons.at[index, 'Home_Last_Game'] = (current_date - last_game_date[home]).days
    last_game_date[home] = current_date  # Update the last game date for this home team

# Display the DataFrame to verify the changes
# print(multiple_seasons)
#In this example, I've set up the DataFrame and columns as described. Then I loop through each row, updating the Visitor_Last_Game and Home_Last_Game columns based on the last_game_date dictionary. Finally, I update the last_game_date dictionary to remember the most recent game for each team.

#This will populate the Visitor_Last_Game and Home_Last_Game columns with the number of days since the last game for the visitor and home teams, respectively. Note that the first game for each team will be set to NaN because there's no prior game to reference.


multiple_seasons.tail(60)

,Date,Visiting Team,Visitor Score,Home Team,Home Score,Visitor_Last_Game,Home_Last_Game
3618,2021-05-14,New Orleans Pelicans,122,Golden State Warriors,125,2,3
3619,2021-05-15,Chicago Bulls,91,Brooklyn Nets,105,2,3
3620,2021-05-15,Los Angeles Lakers,122,Indiana Pacers,115,3,2
3621,2021-05-15,Charlotte Hornets,109,New York Knicks,118,2,2
3622,2021-05-15,Boston Celtics,124,Minnesota Timberwolves,108,3,2
3623,2021-05-15,Phoenix Suns,140,San Antonio Spurs,103,2,2
3624,2021-05-15,Miami Heat,108,Milwaukee Bucks,122,2,2
3625,2021-05-16,Boston Celtics,92,New York Knicks,96,1,1
3626,2021-05-16,Indiana Pacers,125,Toronto Raptors,113,1,2
3627,2021-05-16,Charlotte Hornets,110,Washington Wizards,115,1,2
3628,2021-05-16,Phoenix Suns,123,San Antonio Spurs,121,1,1
3629,2021-05-16,Memphis Grizzlies,101,Golden State Warriors,113,2,2
3630,2021-05-16,Houston Rockets,95,Atlanta Hawks,124,2,3
3631,2021-05-16,Cleveland Cavaliers,109,Brooklyn Nets,123,2,1
3632,2021-05-16,Orlando Magic,117,Philadelphia 76ers,128,2,2
3633,2021-05-16,Miami Heat,120,Detroit Pistons,107,1,2
3634,2021-05-16,Milwaukee Bucks,112,Chicago Bulls,118,1,1
3635,2021-05-16,Dallas Mavericks,121,Minnesota Timberwolves,136,2,1
3636,2021-05-16,Los Angeles Lakers,110,New Orleans Pelicans,98,1,2
3637,2021-05-16,Los Angeles Clippers,112,Oklahoma City Thunder,117,2,2
3638,2021-05-16,Denver Nuggets,116,Portland Trail Blazers,132,2,3
3639,2021-05-16,Utah Jazz,121,Sacramento Kings,99,2,2
3640,2021-05-18,Charlotte Hornets,117,Indiana Pacers,144,2,2
3641,2021-05-18,Washington Wizards,100,Boston Celtics,118,2,2
3642,2021-05-19,San Antonio Spurs,96,Memphis Grizzlies,100,3,3
3643,2021-05-19,Golden State Warriors,100,Los Angeles Lakers,103,3,3
3644,2021-05-20,Indiana Pacers,115,Washington Wizards,142,2,2
3645,2021-05-21,Memphis Grizzlies,117,Golden State Warriors,112,2,2
3646,2021-05-22,Miami Heat,107,Milwaukee Bucks,109,6,6
3647,2021-05-22,Dallas Mavericks,113,Los Angeles Clippers,103,6,6
3648,2021-05-22,Boston Celtics,93,Brooklyn Nets,104,4,6
3649,2021-05-22,Portland Trail Blazers,123,Denver Nuggets,109,6,6
3650,2021-05-23,Washington Wizards,118,Philadelphia 76ers,125,3,7
3651,2021-05-23,Los Angeles Lakers,90,Phoenix Suns,99,4,7
3652,2021-05-23,Atlanta Hawks,107,New York Knicks,105,7,7
3653,2021-05-23,Memphis Grizzlies,112,Utah Jazz,109,2,7
3654,2021-05-24,Miami Heat,98,Milwaukee Bucks,132,2,2
3655,2021-05-24,Portland Trail Blazers,109,Denver Nuggets,128,2,2
3656,2021-05-25,Boston Celtics,108,Brooklyn Nets,130,3,3
3657,2021-05-25,Los Angeles Lakers,109,Phoenix Suns,102,2,2
3658,2021-05-25,Dallas Mavericks,127,Los Angeles Clippers,121,3,3
3659,2021-05-26,Washington Wizards,95,Philadelphia 76ers,120,3,3
3660,2021-05-26,Atlanta Hawks,92,New York Knicks,101,3,3
3661,2021-05-26,Memphis Grizzlies,129,Utah Jazz,141,3,3
3662,2021-05-27,Milwaukee Bucks,113,Miami Heat,84,3,3
3663,2021-05-27,Phoenix Suns,95,Los Angeles Lakers,109,2,2
3664,2021-05-27,Denver Nuggets,120,Portland Trail Blazers,115,3,3
3665,2021-05-28,New York Knicks,94,Atlanta Hawks,105,2,2
3666,2021-05-28,Brooklyn Nets,119,Boston Celtics,125,3,3
3667,2021-05-28,Los Angeles Clippers,118,Dallas Mavericks,108,3,3
3668,2021-05-29,Milwaukee Bucks,120,Miami Heat,103,2,2
3669,2021-05-29,Denver Nuggets,95,Portland Trail Blazers,115,2,2
3670,2021-05-29,Philadelphia 76ers,132,Washington Wizards,103,3,3
3671,2021-05-29,Utah Jazz,121,Memphis Grizzlies,111,3,3
3672,2021-05-30,New York Knicks,96,Atlanta Hawks,113,2,2
3673,2021-05-30,Phoenix Suns,100,Los Angeles Lakers,92,3,3
3674,2021-05-30,Brooklyn Nets,141,Boston Celtics,126,2,2
3675,2021-05-30,Los Angeles Clippers,106,Dallas Mavericks,81,2,2
3676,2021-05-31,Philadelphia 76ers,114,Washington Wizards,122,2,2
3677,2021-05-31,Utah Jazz,120,Memphis Grizzlies,113,2,2