In [28]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import pandas as pd
from sklearn.datasets import make_moons

#  Import nba data
nba_gamestats_df = pd.read_csv("Basketball_Data/curated_game_stats.csv")
print(nba_gamestats_df.head())

nba_advancedgame_df = pd.read_csv("Basketball_Data/Advanced_Game_Stats_2001-2003.csv")
nba_advancedgame_df.head()

   Unnamed: 0 Team        Date  PTS  Opp  FG  FGA 2PA  3P 3PA Opponent_Points
0           0  SAC  2023-02-24  176  LAC  65  111  70  18  41             175
1           1  LAC  2023-02-24  175  SAC  59   98  53  26  45             176
2           2  CHO  2022-01-26  158  IND  54   93  48  24  45             126
3           3  GSW  2023-04-09  157  POR  58   96  47  27  49             101
4           4  SAS  2022-02-25  157  WAS  57  105  76   9  29             153

,Rk,Team,Date,eFG%,Unnamed: 4,Opp,Result,ORtg,FTr,3PAr,TS%,eFG%.1,FT/FGA,ORtg.1,FTr.1,3PAr.1,TS%.1,eFG%.2,FT/FGA.1
0,1,DAL,2021-12-01,0.795,@,NOP,W 139-107,152.3,0.108,0.410,0.799,0.795,0.084,117.2,0.180,0.416,0.557,0.522,0.157
1,2,MIN,2022-12-18,0.787,NaN,CHI,W 150-126,147.9,0.184,0.494,0.798,0.787,0.149,124.2,0.273,0.432,0.639,0.614,0.205
2,3,MIN,2022-10-26,0.775,NaN,SAS,W 134-122,131.1,0.200,0.425,0.770,0.775,0.125,119.3,0.232,0.379,0.583,0.537,0.211
3,4,BRK,2022-12-21,0.768,NaN,GSW,W 143-113,139.8,0.190,0.393,0.785,0.768,0.167,110.5,0.301,0.398,0.601,0.566,0.229
4,5,LAC,2023-03-29,0.756,@,MEM,W 141-132,137.1,0.397,0.474,0.769,0.756,0.295,128.3,0.295,0.337,0.615,0.574,0.242

In [29]:
#Check types for nba game stats
nba_gamestats_df.dtypes

Unnamed: 0          int64
Team               object
Date               object
PTS                object
Opp                object
FG                 object
FGA                object
2PA                object
3P                 object
3PA                object
Opponent_Points    object
dtype: object

In [30]:
#Check types for nba advanced stats
nba_advancedgame_df.dtypes

Rk              int64
Team           object
Date           object
eFG%          float64
Unnamed: 4     object
Opp            object
Result         object
ORtg          float64
FTr           float64
3PAr          float64
TS%           float64
eFG%.1        float64
FT/FGA        float64
ORtg.1        float64
FTr.1         float64
3PAr.1        float64
TS%.1         float64
eFG%.2        float64
FT/FGA.1      float64
dtype: object

In [31]:
#Test matching dates needed for merge
nba_gamestats_df.loc[nba_gamestats_df["Date"] == nba_advancedgame_df["Date"][0]]

,Unnamed: 0,Team,Date,PTS,Opp,FG,FGA,2PA,3P,3PA,Opponent_Points
101,101,DAL,2021-12-01,139,NOP,57,83,49,18,34,107
650,650,MIL,2021-12-01,127,CHO,46,94,58,14,36,125
820,820,CHO,2021-12-01,125,MIL,43,87,36,21,51,127
924,924,SAC,2021-12-01,124,LAC,46,88,50,15,38,115
2107,2107,LAC,2021-12-01,115,SAC,47,100,69,9,31,124
2108,2108,WAS,2021-12-01,115,MIN,45,91,59,10,32,107
2278,2278,ATL,2021-12-01,114,IND,44,86,53,16,33,111
2279,2279,HOU,2021-12-01,114,OKC,40,79,42,15,37,110
2772,2772,CLE,2021-12-01,111,MIA,37,68,37,16,31,85
2773,2773,IND,2021-12-01,111,ATL,44,90,57,10,33,114
2930,2930,OKC,2021-12-01,110,HOU,40,85,53,8,32,114
3242,3242,ORL,2021-12-01,108,DEN,44,81,54,6,27,103
3358,3358,NOP,2021-12-01,107,DAL,40,89,52,13,37,139
3359,3359,MIN,2021-12-01,107,WAS,37,88,51,11,37,115
3871,3871,DEN,2021-12-01,103,ORL,39,80,46,10,34,108
4827,4827,BOS,2021-12-01,88,PHI,33,79,51,11,28,87
4847,4847,PHI,2021-12-01,87,BOS,33,89,58,8,31,88
4874,4874,MIA,2021-12-01,85,CLE,32,85,48,12,37,111

In [32]:
#Drop columns not needed, rename column
nba_advancedgame_df = nba_advancedgame_df.drop(["Result", "Rk", "FTr",	'3PAr',	'eFG%.1',	'FT/FGA',	'ORtg.1',	'FTr.1',	'3PAr.1',	'TS%.1',	'eFG%.2',	'FT/FGA.1'], axis=1)

nba_advancedgame_df.rename({
  "Unnamed: 4" : "Home/Away"
}, axis=1, inplace=True)


nba_advancedgame_df.head()

  Team        Date   eFG% Home/Away  Opp   ORtg    TS%
0  DAL  2021-12-01  0.795         @  NOP  152.3  0.799
1  MIN  2022-12-18  0.787       NaN  CHI  147.9  0.798
2  MIN  2022-10-26  0.775       NaN  SAS  131.1  0.770
3  BRK  2022-12-21  0.768       NaN  GSW  139.8  0.785
4  LAC  2023-03-29  0.756         @  MEM  137.1  0.769

In [33]:
#Drop columns not needed
nba_gamestats_df = nba_gamestats_df.drop(["Unnamed: 0"], axis=1)

nba_gamestats_df.head()

  Team        Date  PTS  Opp  FG  FGA 2PA  3P 3PA Opponent_Points
0  SAC  2023-02-24  176  LAC  65  111  70  18  41             175
1  LAC  2023-02-24  175  SAC  59   98  53  26  45             176
2  CHO  2022-01-26  158  IND  54   93  48  24  45             126
3  GSW  2023-04-09  157  POR  58   96  47  27  49             101
4  SAS  2022-02-25  157  WAS  57  105  76   9  29             153

In [34]:
complete_stats_df = pd.merge(nba_gamestats_df, nba_advancedgame_df, on=["Date", "Team", "Opp"])

In [35]:
complete_stats_df

,Team,Date,PTS,Opp,FG,FGA,2PA,3P,3PA,Opponent_Points,eFG%,Home/Away,ORtg,TS%
0,SAC,2023-02-24,176,LAC,65,111,70,18,41,175,0.667,@,136.9,0.696
1,LAC,2023-02-24,175,SAC,59,98,53,26,45,176,0.735,NaN,136.1,0.769
2,CHO,2022-01-26,158,IND,54,93,48,24,45,126,0.710,@,147.7,0.735
3,GSW,2023-04-09,157,POR,58,96,47,27,49,101,0.745,@,143.9,0.762
4,SAS,2022-02-25,157,WAS,57,105,76,9,29,153,0.586,@,130.7,0.633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,DAL,2022-03-09,77,NYK,27,86,42,6,44,107,0.349,NaN,86.3,0.397
4916,CHI,2021-11-22,77,IND,31,85,57,6,28,109,0.400,NaN,81.3,0.420
4917,SAC,2022-01-25,75,BOS,29,95,62,6,33,128,0.337,@,78.4,0.369
4918,NYK,2022-01-08,75,BOS,29,79,48,11,31,99,0.437,@,89.7,0.438
4919,DAL,2021-10-29,75,DEN,23,78,41,8,37,106,0.346,@,75.7,0.417

In [36]:
#Transform Dataframe
complete_stats_df=complete_stats_df.astype({
  'PTS' : 'float',
  'Opponent_Points' : 'float',
  'Home/Away': 'string',
  'FG': 'float',
  'FGA': 'float',
  '2PA': 'float',
  '3P': 'float',
  '3PA': 'float',
  'Team': 'string',
  'Opp': 'string'
})

complete_stats_df.dtypes

Team                string
Date                object
PTS                float64
Opp                 string
FG                 float64
FGA                float64
2PA                float64
3P                 float64
3PA                float64
Opponent_Points    float64
eFG%               float64
Home/Away           string
ORtg               float64
TS%                float64
dtype: object

In [45]:
#Add Column and convert home/away
complete_stats_df["Pts Difference"] = complete_stats_df["PTS"] - complete_stats_df["Opponent_Points"]
complete_stats_df['Home/Away'] = complete_stats_df['Home/Away'].replace(['@', ''], ['Away', 'Home'])
complete_stats_df['Home/Away'].fillna(value="Home", inplace=True)

complete_stats_df.head()

,Team,Date,PTS,Opp,FG,FGA,2PA,3P,3PA,Opponent_Points,eFG%,Home/Away,ORtg,TS%,Pts Difference
0,SAC,2023-02-24,176.0,LAC,65.0,111.0,70.0,18.0,41.0,175.0,0.667,Away,136.9,0.696,1.0
1,LAC,2023-02-24,175.0,SAC,59.0,98.0,53.0,26.0,45.0,176.0,0.735,Home,136.1,0.769,-1.0
2,CHO,2022-01-26,158.0,IND,54.0,93.0,48.0,24.0,45.0,126.0,0.710,Away,147.7,0.735,32.0
3,GSW,2023-04-09,157.0,POR,58.0,96.0,47.0,27.0,49.0,101.0,0.745,Away,143.9,0.762,56.0
4,SAS,2022-02-25,157.0,WAS,57.0,105.0,76.0,9.0,29.0,153.0,0.586,Away,130.7,0.633,4.0

In [47]:
complete_stats_df.drop(["Date"], axis=1, inplace=True)

In [48]:
complete_stats_df.head()

,Team,PTS,Opp,FG,FGA,2PA,3P,3PA,Opponent_Points,eFG%,Home/Away,ORtg,TS%,Pts Difference
0,SAC,176.0,LAC,65.0,111.0,70.0,18.0,41.0,175.0,0.667,Away,136.9,0.696,1.0
1,LAC,175.0,SAC,59.0,98.0,53.0,26.0,45.0,176.0,0.735,Home,136.1,0.769,-1.0
2,CHO,158.0,IND,54.0,93.0,48.0,24.0,45.0,126.0,0.710,Away,147.7,0.735,32.0
3,GSW,157.0,POR,58.0,96.0,47.0,27.0,49.0,101.0,0.745,Away,143.9,0.762,56.0
4,SAS,157.0,WAS,57.0,105.0,76.0,9.0,29.0,153.0,0.586,Away,130.7,0.633,4.0

In [49]:
# Split our preprocessed data into our features and target arrays
y = complete_stats_df['Pts Difference']
X = complete_stats_df.drop(['Pts Difference'], axis=1)

In [50]:
#One Hot Encoding
X = pd.get_dummies(X, columns=["Team", "Opp", "Home/Away"])

In [54]:
X.head()

,PTS,FG,FGA,2PA,3P,3PA,Opponent_Points,eFG%,ORtg,TS%,...,Opp_PHI,Opp_PHO,Opp_POR,Opp_SAC,Opp_SAS,Opp_TOR,Opp_UTA,Opp_WAS,Home/Away_Away,Home/Away_Home
0,176.0,65.0,111.0,70.0,18.0,41.0,175.0,0.667,136.9,0.696,...,0,0,0,0,0,0,0,0,1,0
1,175.0,59.0,98.0,53.0,26.0,45.0,176.0,0.735,136.1,0.769,...,0,0,0,1,0,0,0,0,0,1
2,158.0,54.0,93.0,48.0,24.0,45.0,126.0,0.710,147.7,0.735,...,0,0,0,0,0,0,0,0,1,0
3,157.0,58.0,96.0,47.0,27.0,49.0,101.0,0.745,143.9,0.762,...,0,0,1,0,0,0,0,0,1,0
4,157.0,57.0,105.0,76.0,9.0,29.0,153.0,0.586,130.7,0.633,...,0,0,0,0,0,0,0,1,1,0

In [80]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42)

In [81]:
# Create a StandardScaler instances
scaler = StandardScaler()


# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [95]:
#Instantiate Neural Network Model
nn_model = tf.keras.models.Sequential()

unit = 2 * X_train_scaled.shape[1]

#Dense Layers
nn_model.add(tf.keras.layers.Dense(units=unit, activation="elu", input_dim=X_train_scaled.shape[1]))
nn_model.add(tf.keras.layers.Dense(units=unit/4, activation="elu"))


#Output Layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="linear"))

In [96]:
#Summary of Neural Network
nn_model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 144)               10512

 dense_31 (Dense)            (None, 36)                5220

 dense_32 (Dense)            (None, 1)                 37

=================================================================
Total params: 15769 (61.60 KB)
Trainable params: 15769 (61.60 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [97]:
#Compile the model
nn_model.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])

#Train model
fit_model = nn_model.fit(X_train, y_train, epochs=200)

Epoch 1/200
116/116 [==============================] - 0s 562us/step - loss: 61.5570 - accuracy: 0.0087
Epoch 2/200
116/116 [==============================] - 0s 515us/step - loss: 1.9192 - accuracy: 0.0103
Epoch 3/200
116/116 [==============================] - 0s 515us/step - loss: 0.8937 - accuracy: 0.0095
Epoch 4/200
116/116 [==============================] - 0s 529us/step - loss: 0.5654 - accuracy: 0.0114
Epoch 5/200
116/116 [==============================] - 0s 536us/step - loss: 0.2205 - accuracy: 0.0146
Epoch 6/200
116/116 [==============================] - 0s 512us/step - loss: 0.1164 - accuracy: 0.0163
Epoch 7/200
116/116 [==============================] - 0s 534us/step - loss: 0.0485 - accuracy: 0.0173
Epoch 8/200
116/116 [==============================] - 0s 552us/step - loss: 0.0344 - accuracy: 0.0173
Epoch 9/200
116/116 [==============================] - 0s 540us/step - loss: 0.0294 - accuracy: 0.0173
Epoch 10/200
116/116 [==============================] - 0s 553us/step - loss: 0.0446 - accuracy: 0.0173
Epoch 11/200
116/116 [==============================] - 0s 541us/step - loss: 0.0297 - accuracy: 0.0173
Epoch 12/200
116/116 [==============================] - 0s 539us/step - loss: 0.0321 - accuracy: 0.0173
Epoch 13/200
116/116 [==============================] - 0s 512us/step - loss: 0.0405 - accuracy: 0.0173
Epoch 14/200
116/116 [==============================] - 0s 513us/step - loss: 0.0835 - accuracy: 0.0168
Epoch 15/200
116/116 [==============================] - 0s 522us/step - loss: 0.1185 - accuracy: 0.0171
Epoch 16/200
116/116 [==============================] - 0s 597us/step - loss: 0.0657 - accuracy: 0.0171
Epoch 17/200
116/116 [==============================] - 0s 517us/step - loss: 0.0989 - accuracy: 0.0163
Epoch 18/200
116/116 [==============================] - 0s 521us/step - loss: 0.1117 - accuracy: 0.0157
Epoch 19/200
116/116 [==============================] - 0s 514us/step - loss: 0.1199 - accuracy: 0.0165
Epoch 20/200
116/116 [==============================] - 0s 533us/step - loss: 0.1424 - accuracy: 0.0165
Epoch 21/200
116/116 [==============================] - 0s 500us/step - loss: 0.1274 - accuracy: 0.0163
Epoch 22/200
116/116 [==============================] - 0s 518us/step - loss: 0.1877 - accuracy: 0.0149
Epoch 23/200
116/116 [==============================] - 0s 514us/step - loss: 0.0232 - accuracy: 0.0173
Epoch 24/200
116/116 [==============================] - 0s 530us/step - loss: 0.1484 - accuracy: 0.0163
Epoch 25/200
116/116 [==============================] - 0s 536us/step - loss: 0.1118 - accuracy: 0.0165
Epoch 26/200
116/116 [==============================] - 0s 511us/step - loss: 0.0843 - accuracy: 0.0165
Epoch 27/200
116/116 [==============================] - 0s 512us/step - loss: 0.0730 - accuracy: 0.0168
Epoch 28/200
116/116 [==============================] - 0s 512us/step - loss: 0.1359 - accuracy: 0.0163
Epoch 29/200
116/116 [==============================] - 0s 515us/step - loss: 0.1822 - accuracy: 0.0141
Epoch 30/200
116/116 [==============================] - 0s 518us/step - loss: 0.0781 - accuracy: 0.0168
Epoch 31/200
116/116 [==============================] - 0s 514us/step - loss: 0.0661 - accuracy: 0.0165
Epoch 32/200
116/116 [==============================] - 0s 515us/step - loss: 0.1057 - accuracy: 0.0160
Epoch 33/200
116/116 [==============================] - 0s 515us/step - loss: 0.0798 - accuracy: 0.0165
Epoch 34/200
116/116 [==============================] - 0s 523us/step - loss: 0.1998 - accuracy: 0.0160
Epoch 35/200
116/116 [==============================] - 0s 563us/step - loss: 0.0386 - accuracy: 0.0173
Epoch 36/200
116/116 [==============================] - 0s 512us/step - loss: 0.1094 - accuracy: 0.0163
Epoch 37/200
116/116 [==============================] - 0s 518us/step - loss: 0.1606 - accuracy: 0.0157
Epoch 38/200
116/116 [==============================] - 0s 502us/step - loss: 0.0630 - accuracy: 0.0171
Epoch 39/200
116/116 [==============================] - 0s 535us/step - loss: 0.2406 - accuracy: 0.0144
Epoch 40/200
116/116 [==============================] - 0s 571us/step - loss: 0.1597 - accuracy: 0.0154
Epoch 41/200
116/116 [==============================] - 0s 582us/step - loss: 0.0098 - accuracy: 0.0173
Epoch 42/200
116/116 [==============================] - 0s 522us/step - loss: 0.0509 - accuracy: 0.0168
Epoch 43/200
116/116 [==============================] - 0s 547us/step - loss: 0.1310 - accuracy: 0.0144
Epoch 44/200
116/116 [==============================] - 0s 537us/step - loss: 0.1776 - accuracy: 0.0160
Epoch 45/200
116/116 [==============================] - 0s 516us/step - loss: 0.0404 - accuracy: 0.0171
Epoch 46/200
116/116 [==============================] - 0s 508us/step - loss: 0.0499 - accuracy: 0.0171
Epoch 47/200
116/116 [==============================] - 0s 534us/step - loss: 0.1335 - accuracy: 0.0163
Epoch 48/200
116/116 [==============================] - 0s 517us/step - loss: 0.0910 - accuracy: 0.0168
Epoch 49/200
116/116 [==============================] - 0s 516us/step - loss: 0.0649 - accuracy: 0.0168
Epoch 50/200
116/116 [==============================] - 0s 521us/step - loss: 0.1295 - accuracy: 0.0160
Epoch 51/200
116/116 [==============================] - 0s 531us/step - loss: 0.0730 - accuracy: 0.0165
Epoch 52/200
116/116 [==============================] - 0s 529us/step - loss: 0.1191 - accuracy: 0.0154
Epoch 53/200
116/116 [==============================] - 0s 512us/step - loss: 0.1734 - accuracy: 0.0152
Epoch 54/200
116/116 [==============================] - 0s 576us/step - loss: 0.0195 - accuracy: 0.0173
Epoch 55/200
116/116 [==============================] - 0s 509us/step - loss: 0.1153 - accuracy: 0.0160
Epoch 56/200
116/116 [==============================] - 0s 543us/step - loss: 0.1655 - accuracy: 0.0152
Epoch 57/200
116/116 [==============================] - 0s 522us/step - loss: 0.0225 - accuracy: 0.0173
Epoch 58/200
116/116 [==============================] - 0s 528us/step - loss: 0.0498 - accuracy: 0.0171
Epoch 59/200
116/116 [==============================] - 0s 513us/step - loss: 0.0814 - accuracy: 0.0171
Epoch 60/200
116/116 [==============================] - 0s 515us/step - loss: 0.1283 - accuracy: 0.0168
Epoch 61/200
116/116 [==============================] - 0s 513us/step - loss: 0.1074 - accuracy: 0.0163
Epoch 62/200
116/116 [==============================] - 0s 489us/step - loss: 0.0558 - accuracy: 0.0173
Epoch 63/200
116/116 [==============================] - 0s 517us/step - loss: 0.1503 - accuracy: 0.0157
Epoch 64/200
116/116 [==============================] - 0s 521us/step - loss: 0.0515 - accuracy: 0.0173
Epoch 65/200
116/116 [==============================] - 0s 526us/step - loss: 0.0793 - accuracy: 0.0168
Epoch 66/200
116/116 [==============================] - 0s 515us/step - loss: 0.1432 - accuracy: 0.0154
Epoch 67/200
116/116 [==============================] - 0s 523us/step - loss: 0.0204 - accuracy: 0.0173
Epoch 68/200
116/116 [==============================] - 0s 512us/step - loss: 0.0874 - accuracy: 0.0171
Epoch 69/200
116/116 [==============================] - 0s 516us/step - loss: 0.1450 - accuracy: 0.0154
Epoch 70/200
116/116 [==============================] - 0s 523us/step - loss: 0.0736 - accuracy: 0.0168
Epoch 71/200
116/116 [==============================] - 0s 513us/step - loss: 0.0308 - accuracy: 0.0171
Epoch 72/200
116/116 [==============================] - 0s 584us/step - loss: 0.1673 - accuracy: 0.0160
Epoch 73/200
116/116 [==============================] - 0s 514us/step - loss: 0.0273 - accuracy: 0.0173
Epoch 74/200
116/116 [==============================] - 0s 530us/step - loss: 0.0970 - accuracy: 0.0163
Epoch 75/200
116/116 [==============================] - 0s 513us/step - loss: 0.0690 - accuracy: 0.0163
Epoch 76/200
116/116 [==============================] - 0s 511us/step - loss: 0.1107 - accuracy: 0.0157
Epoch 77/200
116/116 [==============================] - 0s 515us/step - loss: 0.0486 - accuracy: 0.0173
Epoch 78/200
116/116 [==============================] - 0s 524us/step - loss: 0.1454 - accuracy: 0.0160
Epoch 79/200
116/116 [==============================] - 0s 514us/step - loss: 0.0100 - accuracy: 0.0173
Epoch 80/200
116/116 [==============================] - 0s 528us/step - loss: 0.0792 - accuracy: 0.0168
Epoch 81/200
116/116 [==============================] - 0s 530us/step - loss: 0.2486 - accuracy: 0.0144
Epoch 82/200
116/116 [==============================] - 0s 526us/step - loss: 0.0078 - accuracy: 0.0173
Epoch 83/200
116/116 [==============================] - 0s 509us/step - loss: 0.0193 - accuracy: 0.0173
Epoch 84/200
116/116 [==============================] - 0s 531us/step - loss: 0.1107 - accuracy: 0.0165
Epoch 85/200
116/116 [==============================] - 0s 528us/step - loss: 0.0528 - accuracy: 0.0171
Epoch 86/200
116/116 [==============================] - 0s 548us/step - loss: 0.1258 - accuracy: 0.0165
Epoch 87/200
116/116 [==============================] - 0s 505us/step - loss: 0.0354 - accuracy: 0.0173
Epoch 88/200
116/116 [==============================] - 0s 524us/step - loss: 0.0978 - accuracy: 0.0163
Epoch 89/200
116/116 [==============================] - 0s 563us/step - loss: 0.0521 - accuracy: 0.0173
Epoch 90/200
116/116 [==============================] - 0s 531us/step - loss: 0.0548 - accuracy: 0.0173
Epoch 91/200
116/116 [==============================] - 0s 519us/step - loss: 0.1108 - accuracy: 0.0165
Epoch 92/200
116/116 [==============================] - 0s 521us/step - loss: 0.0618 - accuracy: 0.0171
Epoch 93/200
116/116 [==============================] - 0s 522us/step - loss: 0.0500 - accuracy: 0.0173
Epoch 94/200
116/116 [==============================] - 0s 513us/step - loss: 0.1439 - accuracy: 0.0144
Epoch 95/200
116/116 [==============================] - 0s 509us/step - loss: 0.0122 - accuracy: 0.0173
Epoch 96/200
116/116 [==============================] - 0s 502us/step - loss: 0.1368 - accuracy: 0.0163
Epoch 97/200
116/116 [==============================] - 0s 509us/step - loss: 0.0216 - accuracy: 0.0173
Epoch 98/200
116/116 [==============================] - 0s 518us/step - loss: 0.0464 - accuracy: 0.0171
Epoch 99/200
116/116 [==============================] - 0s 511us/step - loss: 0.1085 - accuracy: 0.0160
Epoch 100/200
116/116 [==============================] - 0s 513us/step - loss: 0.0780 - accuracy: 0.0163
Epoch 101/200
116/116 [==============================] - 0s 519us/step - loss: 0.0562 - accuracy: 0.0171
Epoch 102/200
116/116 [==============================] - 0s 521us/step - loss: 0.1355 - accuracy: 0.0146
Epoch 103/200
116/116 [==============================] - 0s 512us/step - loss: 0.0326 - accuracy: 0.0173
Epoch 104/200
116/116 [==============================] - 0s 508us/step - loss: 0.0666 - accuracy: 0.0171
Epoch 105/200
116/116 [==============================] - 0s 542us/step - loss: 0.0620 - accuracy: 0.0171
Epoch 106/200
116/116 [==============================] - 0s 513us/step - loss: 0.0894 - accuracy: 0.0165
Epoch 107/200
116/116 [==============================] - 0s 584us/step - loss: 0.1122 - accuracy: 0.0163
Epoch 108/200
116/116 [==============================] - 0s 508us/step - loss: 0.0227 - accuracy: 0.0173
Epoch 109/200
116/116 [==============================] - 0s 505us/step - loss: 0.0778 - accuracy: 0.0157
Epoch 110/200
116/116 [==============================] - 0s 508us/step - loss: 0.1374 - accuracy: 0.0160
Epoch 111/200
116/116 [==============================] - 0s 513us/step - loss: 0.0151 - accuracy: 0.0173
Epoch 112/200
116/116 [==============================] - 0s 518us/step - loss: 0.0418 - accuracy: 0.0173
Epoch 113/200
116/116 [==============================] - 0s 523us/step - loss: 0.0911 - accuracy: 0.0168
Epoch 114/200
116/116 [==============================] - 0s 509us/step - loss: 0.0743 - accuracy: 0.0171
Epoch 115/200
116/116 [==============================] - 0s 500us/step - loss: 0.0481 - accuracy: 0.0171
Epoch 116/200
116/116 [==============================] - 0s 505us/step - loss: 0.0473 - accuracy: 0.0171
Epoch 117/200
116/116 [==============================] - 0s 531us/step - loss: 0.1486 - accuracy: 0.0154
Epoch 118/200
116/116 [==============================] - 0s 514us/step - loss: 0.0091 - accuracy: 0.0173
Epoch 119/200
116/116 [==============================] - 0s 524us/step - loss: 0.0637 - accuracy: 0.0171
Epoch 120/200
116/116 [==============================] - 0s 518us/step - loss: 0.0535 - accuracy: 0.0168
Epoch 121/200
116/116 [==============================] - 0s 542us/step - loss: 0.0651 - accuracy: 0.0173
Epoch 122/200
116/116 [==============================] - 0s 514us/step - loss: 0.0982 - accuracy: 0.0165
Epoch 123/200
116/116 [==============================] - 0s 572us/step - loss: 0.0460 - accuracy: 0.0171
Epoch 124/200
116/116 [==============================] - 0s 516us/step - loss: 0.0731 - accuracy: 0.0171
Epoch 125/200
116/116 [==============================] - 0s 521us/step - loss: 0.0539 - accuracy: 0.0173
Epoch 126/200
116/116 [==============================] - 0s 519us/step - loss: 0.0796 - accuracy: 0.0171
Epoch 127/200
116/116 [==============================] - 0s 545us/step - loss: 0.0390 - accuracy: 0.0173
Epoch 128/200
116/116 [==============================] - 0s 507us/step - loss: 0.0891 - accuracy: 0.0168
Epoch 129/200
116/116 [==============================] - 0s 529us/step - loss: 0.0794 - accuracy: 0.0171
Epoch 130/200
116/116 [==============================] - 0s 502us/step - loss: 0.0322 - accuracy: 0.0171
Epoch 131/200
116/116 [==============================] - 0s 500us/step - loss: 0.0846 - accuracy: 0.0163
Epoch 132/200
116/116 [==============================] - 0s 517us/step - loss: 0.0834 - accuracy: 0.0165
Epoch 133/200
116/116 [==============================] - 0s 520us/step - loss: 0.0117 - accuracy: 0.0173
Epoch 134/200
116/116 [==============================] - 0s 555us/step - loss: 0.0744 - accuracy: 0.0165
Epoch 135/200
116/116 [==============================] - 0s 524us/step - loss: 0.1155 - accuracy: 0.0149
Epoch 136/200
116/116 [==============================] - 0s 504us/step - loss: 0.0285 - accuracy: 0.0173
Epoch 137/200
116/116 [==============================] - 0s 564us/step - loss: 0.0157 - accuracy: 0.0173
Epoch 138/200
116/116 [==============================] - 0s 576us/step - loss: 0.1270 - accuracy: 0.0163
Epoch 139/200
116/116 [==============================] - 0s 518us/step - loss: 0.0327 - accuracy: 0.0173
Epoch 140/200
116/116 [==============================] - 0s 524us/step - loss: 0.0467 - accuracy: 0.0168
Epoch 141/200
116/116 [==============================] - 0s 507us/step - loss: 0.0909 - accuracy: 0.0165
Epoch 142/200
116/116 [==============================] - 0s 513us/step - loss: 0.0336 - accuracy: 0.0171
Epoch 143/200
116/116 [==============================] - 0s 513us/step - loss: 0.0863 - accuracy: 0.0171
Epoch 144/200
116/116 [==============================] - 0s 518us/step - loss: 0.0264 - accuracy: 0.0173
Epoch 145/200
116/116 [==============================] - 0s 514us/step - loss: 0.1761 - accuracy: 0.0160
Epoch 146/200
116/116 [==============================] - 0s 522us/step - loss: 0.0196 - accuracy: 0.0173
Epoch 147/200
116/116 [==============================] - 0s 513us/step - loss: 0.0069 - accuracy: 0.0173
Epoch 148/200
116/116 [==============================] - 0s 523us/step - loss: 0.0743 - accuracy: 0.0160
Epoch 149/200
116/116 [==============================] - 0s 529us/step - loss: 0.0541 - accuracy: 0.0171
Epoch 150/200
116/116 [==============================] - 0s 526us/step - loss: 0.0237 - accuracy: 0.0171
Epoch 151/200
116/116 [==============================] - 0s 513us/step - loss: 0.1142 - accuracy: 0.0146
Epoch 152/200
116/116 [==============================] - 0s 521us/step - loss: 0.0532 - accuracy: 0.0173
Epoch 153/200
116/116 [==============================] - 0s 595us/step - loss: 0.0302 - accuracy: 0.0173
Epoch 154/200
116/116 [==============================] - 0s 522us/step - loss: 0.0422 - accuracy: 0.0165
Epoch 155/200
116/116 [==============================] - 0s 515us/step - loss: 0.0635 - accuracy: 0.0163
Epoch 156/200
116/116 [==============================] - 0s 533us/step - loss: 0.0352 - accuracy: 0.0173
Epoch 157/200
116/116 [==============================] - 0s 515us/step - loss: 0.0835 - accuracy: 0.0168
Epoch 158/200
116/116 [==============================] - 0s 506us/step - loss: 0.0568 - accuracy: 0.0171
Epoch 159/200
116/116 [==============================] - 0s 503us/step - loss: 0.0180 - accuracy: 0.0173
Epoch 160/200
116/116 [==============================] - 0s 512us/step - loss: 0.1123 - accuracy: 0.0165
Epoch 161/200
116/116 [==============================] - 0s 524us/step - loss: 0.0607 - accuracy: 0.0168
Epoch 162/200
116/116 [==============================] - 0s 554us/step - loss: 0.0188 - accuracy: 0.0173
Epoch 163/200
116/116 [==============================] - 0s 522us/step - loss: 0.0496 - accuracy: 0.0173
Epoch 164/200
116/116 [==============================] - 0s 523us/step - loss: 0.0797 - accuracy: 0.0171
Epoch 165/200
116/116 [==============================] - 0s 572us/step - loss: 0.0386 - accuracy: 0.0173
Epoch 166/200
116/116 [==============================] - 0s 625us/step - loss: 0.0351 - accuracy: 0.0173
Epoch 167/200
116/116 [==============================] - 0s 543us/step - loss: 0.0446 - accuracy: 0.0168
Epoch 168/200
116/116 [==============================] - 0s 613us/step - loss: 0.0931 - accuracy: 0.0165
Epoch 169/200
116/116 [==============================] - 0s 538us/step - loss: 0.0267 - accuracy: 0.0173
Epoch 170/200
116/116 [==============================] - 0s 549us/step - loss: 0.1180 - accuracy: 0.0160
Epoch 171/200
116/116 [==============================] - 0s 540us/step - loss: 0.0137 - accuracy: 0.0173
Epoch 172/200
116/116 [==============================] - 0s 529us/step - loss: 0.0237 - accuracy: 0.0173
Epoch 173/200
116/116 [==============================] - 0s 524us/step - loss: 0.1012 - accuracy: 0.0163
Epoch 174/200
116/116 [==============================] - 0s 530us/step - loss: 0.0111 - accuracy: 0.0173
Epoch 175/200
116/116 [==============================] - 0s 522us/step - loss: 0.0416 - accuracy: 0.0173
Epoch 176/200
116/116 [==============================] - 0s 526us/step - loss: 0.0778 - accuracy: 0.0168
Epoch 177/200
116/116 [==============================] - 0s 519us/step - loss: 0.0425 - accuracy: 0.0173
Epoch 178/200
116/116 [==============================] - 0s 509us/step - loss: 0.0126 - accuracy: 0.0173
Epoch 179/200
116/116 [==============================] - 0s 556us/step - loss: 0.1429 - accuracy: 0.0154
Epoch 180/200
116/116 [==============================] - 0s 525us/step - loss: 0.0543 - accuracy: 0.0173
Epoch 181/200
116/116 [==============================] - 0s 568us/step - loss: 0.0278 - accuracy: 0.0173
Epoch 182/200
116/116 [==============================] - 0s 555us/step - loss: 0.0196 - accuracy: 0.0173
Epoch 183/200
116/116 [==============================] - 0s 584us/step - loss: 0.0492 - accuracy: 0.0173
Epoch 184/200
116/116 [==============================] - 0s 686us/step - loss: 0.0719 - accuracy: 0.0173
Epoch 185/200
116/116 [==============================] - 0s 551us/step - loss: 0.0264 - accuracy: 0.0171
Epoch 186/200
116/116 [==============================] - 0s 563us/step - loss: 0.1017 - accuracy: 0.0157
Epoch 187/200
116/116 [==============================] - 0s 543us/step - loss: 0.0219 - accuracy: 0.0173
Epoch 188/200
116/116 [==============================] - 0s 517us/step - loss: 0.0052 - accuracy: 0.0173
Epoch 189/200
116/116 [==============================] - 0s 505us/step - loss: 0.1398 - accuracy: 0.0157
Epoch 190/200
116/116 [==============================] - 0s 524us/step - loss: 0.0499 - accuracy: 0.0173
Epoch 191/200
116/116 [==============================] - 0s 514us/step - loss: 0.0154 - accuracy: 0.0173
Epoch 192/200

In [94]:
#
#
#

model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

39/39 - 0s - loss: 895.1069 - accuracy: 0.0049 - 80ms/epoch - 2ms/step
Loss: 895.10693359375, Accuracy: 0.004878048785030842